apiVersion: v1
kind: Service
metadata:
  name: aw-nginx-web-service
  labels:
    run: aw-nginx-web-service
    tier: front-end
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: aw-nginx-webserver
